# Generated by Django 5.0 on 2024-02-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracedata",
            name="trace_a_unit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracedata",
            name="trace_d_unit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracedata",
            name="trace_v_unit",
            field=models.TextField(blank=True, null=True),
        ),
    ]
