# Generated by Django 5.0 on 2024-03-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calibtraces",
            old_name="iduser",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="calibtraces",
            name="idurlFile",
        ),
        migrations.RemoveField(
            model_name="calibtraces",
            name="stream",
        ),
        migrations.AddField(
            model_name="calibtraces",
            name="calib",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibtraces",
            name="channel",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibtraces",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibtraces",
            name="network",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibtraces",
            name="station",
            field=models.TextField(blank=True, null=True),
        ),
    ]
