# Generated by Django 5.0 on 2024-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracedata",
            name="peak_a",
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tracedata",
            name="peak_d",
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tracedata",
            name="peak_v",
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
