# Generated by Django 5.0 on 2024-04-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="checkM",
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
