# Generated by Django 5.0 on 2024-01-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotdata",
            name="image_path",
            field=models.ImageField(blank=True, null=True, upload_to="seismic_plots/"),
        ),
    ]
