# Generated by Django 5.0 on 2024-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0002_rename_iduser_calibtraces_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibtraces",
            name="calib",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
