# Generated by Django 5.0 on 2024-01-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0002_alter_plotdata_image_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traces", models.JSONField()),
            ],
        ),
    ]
