# Generated by Django 5.0 on 2024-05-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0002_proyecto_checkm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
