# Generated by Django 5.0 on 2024-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0002_tracedata_peak_a_tracedata_peak_d_tracedata_peak_v"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracedata",
            name="peak_a",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracedata",
            name="peak_d",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracedata",
            name="peak_v",
            field=models.TextField(blank=True, null=True),
        ),
    ]
