# Generated by Django 5.0 on 2024-02-13 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0002_tracedata_trace_a_unit_tracedata_trace_d_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeruser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
