# Generated by Django 5.0 on 2024-01-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0003_tracedata"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracedata",
            name="tiempo",
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
