# Generated by Django 5.0 on 2024-02-13 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0003_alter_registeruser_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registeruser",
            name="uuid",
        ),
    ]
