# Generated by Django 5.0 on 2024-02-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0004_remove_registeruser_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracedata",
            name="formato",
            field=models.TextField(blank=True, null=True),
        ),
    ]
