# Generated by Django 5.0 on 2024-01-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0004_tracedata_tiempo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracedata",
            name="tiempo",
            field=models.JSONField(),
        ),
    ]
