# Generated by Django 5.0 on 2024-03-23 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0004_alter_proyecto_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadfile",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadfile",
            name="ip",
            field=models.TextField(blank=True, null=True),
        ),
    ]
