# Generated by Django 5.0 on 2024-01-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0005_alter_tracedata_tiempo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tracedata",
            old_name="tiempo",
            new_name="tiempo_a",
        ),
        migrations.RenameField(
            model_name="tracedata",
            old_name="traces",
            new_name="traces_a",
        ),
        migrations.AddField(
            model_name="tracedata",
            name="traces_v",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
