# Generated by Django 5.0 on 2024-03-23 07:20

import django.db.models.deletion
import restapi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0005_uploadfile_fecha_creacion_uploadfile_ip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProyectoFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userFile",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=restapi.models.user_project_directory_path,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restapi.proyecto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="files",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restapi.proyectofiles"
            ),
        ),
        migrations.DeleteModel(
            name="Files",
        ),
    ]
