# Generated by Django 5.0 on 2024-03-23 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0006_proyectofiles_alter_fileinfo_files_delete_files"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegisterUser",
        ),
        migrations.DeleteModel(
            name="TraceDataBaseline",
        ),
        migrations.DeleteModel(
            name="TraceFilterline",
        ),
        migrations.DeleteModel(
            name="TraceTrimline",
        ),
    ]
