# Generated by Django 5.0 on 2024-03-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0007_delete_registeruser_delete_tracedatabaseline_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proyectofiles",
            old_name="userFile",
            new_name="file",
        ),
        migrations.AddField(
            model_name="proyectofiles",
            name="string_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
