# Generated by Django 5.0 on 2024-02-04 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0010_tracetrimline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                ("typeFile", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Traces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traces_a", models.JSONField()),
                ("traces_v", models.JSONField()),
                ("traces_d", models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="seismicdata",
            name="inv",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="FileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nrNetwork", models.IntegerField()),
                ("nrStations", models.IntegerField()),
                ("unit", models.TextField(blank=True, null=True)),
                ("sensi", models.FloatField()),
                (
                    "files",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="restapi.files"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="files",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restapi.proyecto"
            ),
        ),
        migrations.CreateModel(
            name="StationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network", models.TextField()),
                ("station", models.TextField()),
                ("location", models.TextField()),
                ("channel", models.TextField()),
                ("start_time", models.DateField()),
                ("end_time", models.DateField()),
                ("sampling_rate", models.IntegerField()),
                ("delta", models.FloatField()),
                ("npts", models.IntegerField()),
                ("calib", models.FloatField()),
                ("format", models.TextField()),
                (
                    "fileInfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restapi.fileinfo",
                    ),
                ),
                (
                    "trace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="restapi.traces"
                    ),
                ),
            ],
        ),
    ]
