# Generated by Django 5.0 on 2024-04-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0011_calibtraces_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="tab",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
