# Generated by Django 5.0 on 2024-02-04 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0011_files_proyecto_traces_seismicdata_inv_fileinfo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
