# Generated by Django 5.0 on 2024-02-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0012_proyecto_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="nrNetwork",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="nrStations",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="sensi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="files",
            name="filename",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="files",
            name="typeFile",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="calib",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="channel",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="delta",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="end_time",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="format",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="network",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="npts",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="sampling_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="start_time",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stationinfo",
            name="station",
            field=models.TextField(blank=True, null=True),
        ),
    ]
