# Generated by Django 5.0 on 2024-04-03 20:41

import restapi.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0012_proyecto_tab"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="img",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=restapi.models.user_project_img_directory_path,
            ),
        ),
    ]
