# Generated by Django 5.0 on 2024-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0013_proyecto_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyectofiles",
            name="url_gen",
            field=models.TextField(blank=True, null=True),
        ),
    ]
